{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b44e060c",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "%%writefile app.py\n",
    "\"\"\"\n",
    "AI-Based Intelligent Traffic Monitoring and Smart Traffic Signal Management System\n",
    "Main Streamlit Dashboard\n",
    "\n",
    "Currently running on dummy/simulated data. Live AI modules (detector.py,\n",
    "tracker.py, density.py, etc.) will be wired into the \"Live Detection\" page\n",
    "and the dummy-data generators below will be swapped for database.py reads\n",
    "in a later pass.\n",
    "\"\"\"\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "from datetime import datetime, timedelta\n",
    "import time\n",
    "import random\n",
    "\n",
    "# ============================================================\n",
    "# PAGE CONFIG\n",
    "# ============================================================\n",
    "st.set_page_config(\n",
    "    page_title=\"Smart Traffic Control System\",\n",
    "    page_icon=\"🚦\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\",\n",
    ")\n",
    "\n",
    "# ============================================================\n",
    "# DARK THEME CSS\n",
    "# ============================================================\n",
    "CUSTOM_CSS = \"\"\"\n",
    "<style>\n",
    "    #MainMenu {visibility: hidden;}\n",
    "    footer {visibility: hidden;}\n",
    "    header {visibility: hidden;}\n",
    "\n",
    "    .stApp {\n",
    "        background: linear-gradient(180deg, #0b0f19 0%, #0d1220 100%);\n",
    "        color: #e6e9f0;\n",
    "    }\n",
    "\n",
    "    section[data-testid=\"stSidebar\"] {\n",
    "        background: #0a0e17;\n",
    "        border-right: 1px solid #1c2333;\n",
    "    }\n",
    "    section[data-testid=\"stSidebar\"] .stRadio label {\n",
    "        font-size: 15px;\n",
    "    }\n",
    "\n",
    "    h1, h2, h3, h4 {\n",
    "        color: #f2f4f8 !important;\n",
    "        font-family: 'Segoe UI', sans-serif;\n",
    "    }\n",
    "\n",
    "    /* KPI card */\n",
    "    .kpi-card {\n",
    "        background: linear-gradient(145deg, #131a2b, #0f1524);\n",
    "        border: 1px solid #232b40;\n",
    "        border-radius: 14px;\n",
    "        padding: 18px 20px;\n",
    "        box-shadow: 0 4px 14px rgba(0,0,0,0.35);\n",
    "        transition: transform 0.15s ease;\n",
    "    }\n",
    "    .kpi-card:hover {\n",
    "        transform: translateY(-3px);\n",
    "        border-color: #3b82f6;\n",
    "    }\n",
    "    .kpi-label {\n",
    "        font-size: 13px;\n",
    "        color: #8b94ab;\n",
    "        text-transform: uppercase;\n",
    "        letter-spacing: 0.5px;\n",
    "        margin-bottom: 6px;\n",
    "    }\n",
    "    .kpi-value {\n",
    "        font-size: 30px;\n",
    "        font-weight: 700;\n",
    "        color: #f2f4f8;\n",
    "    }\n",
    "    .kpi-icon {\n",
    "        font-size: 26px;\n",
    "        margin-bottom: 4px;\n",
    "    }\n",
    "    .kpi-sub {\n",
    "        font-size: 12px;\n",
    "        color: #5fd68a;\n",
    "        margin-top: 4px;\n",
    "    }\n",
    "\n",
    "    .status-pill {\n",
    "        display: inline-block;\n",
    "        padding: 6px 16px;\n",
    "        border-radius: 20px;\n",
    "        font-weight: 600;\n",
    "        font-size: 14px;\n",
    "    }\n",
    "\n",
    "    .section-title {\n",
    "        font-size: 20px;\n",
    "        font-weight: 700;\n",
    "        margin-top: 10px;\n",
    "        margin-bottom: 14px;\n",
    "        color: #f2f4f8;\n",
    "        border-left: 4px solid #3b82f6;\n",
    "        padding-left: 10px;\n",
    "    }\n",
    "\n",
    "    .panel {\n",
    "        background: #0f1524;\n",
    "        border: 1px solid #1c2333;\n",
    "        border-radius: 14px;\n",
    "        padding: 18px;\n",
    "    }\n",
    "\n",
    "    div[data-testid=\"stMetricValue\"] {\n",
    "        color: #f2f4f8;\n",
    "    }\n",
    "\n",
    "    .stDataFrame {\n",
    "        border-radius: 10px;\n",
    "        overflow: hidden;\n",
    "    }\n",
    "\n",
    "    .footer-tag {\n",
    "        text-align: center;\n",
    "        color: #4b5470;\n",
    "        font-size: 12px;\n",
    "        margin-top: 40px;\n",
    "    }\n",
    "</style>\n",
    "\"\"\"\n",
    "st.markdown(CUSTOM_CSS, unsafe_allow_html=True)\n",
    "\n",
    "# ============================================================\n",
    "# PLOTLY DARK TEMPLATE\n",
    "# ============================================================\n",
    "PLOTLY_TEMPLATE = \"plotly_dark\"\n",
    "PLOT_BG = \"#0f1524\"\n",
    "PAPER_BG = \"#0f1524\"\n",
    "GRID_COLOR = \"#1c2333\"\n",
    "\n",
    "def style_fig(fig, height=350):\n",
    "    fig.update_layout(\n",
    "        template=PLOTLY_TEMPLATE,\n",
    "        plot_bgcolor=PLOT_BG,\n",
    "        paper_bgcolor=PAPER_BG,\n",
    "        font=dict(color=\"#c8cede\", family=\"Segoe UI\"),\n",
    "        height=height,\n",
    "        margin=dict(l=10, r=10, t=45, b=10),\n",
    "        legend=dict(bgcolor=\"rgba(0,0,0,0)\"),\n",
    "    )\n",
    "    fig.update_xaxes(gridcolor=GRID_COLOR, zerolinecolor=GRID_COLOR)\n",
    "    fig.update_yaxes(gridcolor=GRID_COLOR, zerolinecolor=GRID_COLOR)\n",
    "    return fig\n",
    "\n",
    "DENSITY_COLORS = {\n",
    "    \"Low\": \"#2ecc71\",\n",
    "    \"Medium\": \"#f1c40f\",\n",
    "    \"High\": \"#e67e22\",\n",
    "    \"Very High\": \"#e74c3c\",\n",
    "}\n",
    "VEHICLE_COLORS = {\n",
    "    \"Car\": \"#3b82f6\",\n",
    "    \"Bike\": \"#f1c40f\",\n",
    "    \"Bus\": \"#e67e22\",\n",
    "    \"Truck\": \"#e74c3c\",\n",
    "}\n",
    "\n",
    "# ============================================================\n",
    "# DUMMY DATA GENERATORS\n",
    "# (These are the integration points — later swapped for database.py reads)\n",
    "# ============================================================\n",
    "\n",
    "@st.cache_data(ttl=5)\n",
    "def generate_kpis():\n",
    "    cars = random.randint(120, 220)\n",
    "    bikes = random.randint(60, 140)\n",
    "    bus = random.randint(5, 25)\n",
    "    truck = random.randint(10, 40)\n",
    "    total = cars + bikes + bus + truck\n",
    "    avg_speed = round(random.uniform(28, 58), 1)\n",
    "    density = random.choice([\"Low\", \"Medium\", \"High\", \"Very High\"])\n",
    "    signal = random.choice([\"GREEN\", \"YELLOW\", \"RED\"])\n",
    "    emergency = random.choice([False, False, False, False, True])\n",
    "    return {\n",
    "        \"total\": total, \"cars\": cars, \"bikes\": bikes, \"bus\": bus, \"truck\": truck,\n",
    "        \"avg_speed\": avg_speed, \"density\": density, \"signal\": signal, \"emergency\": emergency,\n",
    "    }\n",
    "\n",
    "@st.cache_data(ttl=30)\n",
    "def generate_hourly_traffic():\n",
    "    hours = [f\"{h:02d}:00\" for h in range(24)]\n",
    "    base = [30, 20, 15, 12, 18, 35, 80, 150, 190, 160, 130, 140,\n",
    "            150, 145, 135, 150, 175, 200, 210, 170, 120, 90, 60, 40]\n",
    "    values = [max(5, b + random.randint(-20, 20)) for b in base]\n",
    "    return pd.DataFrame({\"Hour\": hours, \"Vehicles\": values})\n",
    "\n",
    "@st.cache_data(ttl=30)\n",
    "def generate_density_trend():\n",
    "    now = datetime.now()\n",
    "    times = [(now - timedelta(minutes=5 * i)).strftime(\"%H:%M\") for i in range(30)][::-1]\n",
    "    counts = np.clip(np.cumsum(np.random.randn(30)) * 3 + 25, 2, 60).astype(int)\n",
    "    levels = []\n",
    "    for c in counts:\n",
    "        if c <= 10: levels.append(\"Low\")\n",
    "        elif c <= 25: levels.append(\"Medium\")\n",
    "        elif c <= 40: levels.append(\"High\")\n",
    "        else: levels.append(\"Very High\")\n",
    "    return pd.DataFrame({\"Time\": times, \"VehicleCount\": counts, \"Density\": levels})\n",
    "\n",
    "@st.cache_data(ttl=30)\n",
    "def generate_speed_data():\n",
    "    now = datetime.now()\n",
    "    times = [(now - timedelta(minutes=2 * i)).strftime(\"%H:%M\") for i in range(20)][::-1]\n",
    "    speeds = np.clip(np.random.normal(45, 10, 20), 15, 90)\n",
    "    return pd.DataFrame({\"Time\": times, \"AvgSpeed\": speeds.round(1)})\n",
    "\n",
    "@st.cache_data(ttl=30)\n",
    "def generate_lane_counts():\n",
    "    lanes = [\"Lane 1\", \"Lane 2\", \"Lane 3\"]\n",
    "    counts = [random.randint(15, 60) for _ in lanes]\n",
    "    return pd.DataFrame({\"Lane\": lanes, \"VehicleCount\": counts})\n",
    "\n",
    "@st.cache_data(ttl=30)\n",
    "def generate_vehicle_distribution(kpis):\n",
    "    return pd.DataFrame({\n",
    "        \"Type\": [\"Car\", \"Bike\", \"Bus\", \"Truck\"],\n",
    "        \"Count\": [kpis[\"cars\"], kpis[\"bikes\"], kpis[\"bus\"], kpis[\"truck\"]],\n",
    "    })\n",
    "\n",
    "@st.cache_data(ttl=60)\n",
    "def generate_violation_log():\n",
    "    types = [\"Red Light Violation\", \"Wrong Lane\", \"Illegal Parking\", \"Overspeed\"]\n",
    "    rows = []\n",
    "    now = datetime.now()\n",
    "    for i in range(15):\n",
    "        rows.append({\n",
    "            \"ID\": f\"V{1000+i}\",\n",
    "            \"Type\": random.choice(types),\n",
    "            \"Vehicle ID\": random.randint(1, 300),\n",
    "            \"Time\": (now - timedelta(minutes=random.randint(1, 500))).strftime(\"%Y-%m-%d %H:%M:%S\"),\n",
    "            \"Location\": random.choice([\"Junction A\", \"Junction B\", \"Main St\", \"Ring Rd\"]),\n",
    "        })\n",
    "    return pd.DataFrame(rows).sort_values(\"Time\", ascending=False)\n",
    "\n",
    "@st.cache_data(ttl=60)\n",
    "def generate_prediction_data():\n",
    "    now = datetime.now()\n",
    "    future_times = [(now + timedelta(minutes=5 * i)).strftime(\"%H:%M\") for i in range(1, 7)]\n",
    "    predicted = np.clip(np.cumsum(np.random.randn(6)) * 4 + 90, 20, 220).astype(int)\n",
    "    return pd.DataFrame({\"Time\": future_times, \"PredictedVolume\": predicted})\n",
    "\n",
    "# ============================================================\n",
    "# SIDEBAR NAVIGATION\n",
    "# ============================================================\n",
    "with st.sidebar:\n",
    "    st.markdown(\"## 🚦 TrafficAI\")\n",
    "    st.markdown(\"###### Smart Traffic Control System\")\n",
    "    st.markdown(\"---\")\n",
    "    page = st.radio(\n",
    "        \"Navigation\",\n",
    "        [\"📊 Dashboard\", \"🎥 Live Detection\", \"📈 Analytics\", \"📄 Reports\", \"🔮 Prediction\", \"⚙️ Settings\", \"ℹ️ About\"],\n",
    "        label_visibility=\"collapsed\",\n",
    "    )\n",
    "    st.markdown(\"---\")\n",
    "    st.markdown(\"###### System Status\")\n",
    "    st.markdown(\"🟢 **Online** — Simulated Feed\")\n",
    "    st.caption(f\"Last sync: {datetime.now().strftime('%H:%M:%S')}\")\n",
    "    st.markdown(\"---\")\n",
    "    auto_refresh = st.checkbox(\"Auto-refresh (5s)\", value=False)\n",
    "\n",
    "# ============================================================\n",
    "# REUSABLE KPI CARD COMPONENT\n",
    "# ============================================================\n",
    "def kpi_card(col, icon, label, value, sub=None, color=\"#3b82f6\"):\n",
    "    with col:\n",
    "        st.markdown(f\"\"\"\n",
    "        <div class=\"kpi-card\">\n",
    "            <div class=\"kpi-icon\">{icon}</div>\n",
    "            <div class=\"kpi-label\">{label}</div>\n",
    "            <div class=\"kpi-value\" style=\"color:{color}\">{value}</div>\n",
    "            {f'<div class=\"kpi-sub\">{sub}</div>' if sub else ''}\n",
    "        </div>\n",
    "        \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PAGE: DASHBOARD\n",
    "# ============================================================\n",
    "if page == \"📊 Dashboard\":\n",
    "    st.markdown(\"# Traffic Control Dashboard\")\n",
    "    st.caption(f\"Real-time overview • {datetime.now().strftime('%A, %d %B %Y — %H:%M:%S')}\")\n",
    "\n",
    "    kpis = generate_kpis()\n",
    "\n",
    "    st.markdown('<div class=\"section-title\">Live Metrics</div>', unsafe_allow_html=True)\n",
    "    c1, c2, c3, c4, c5 = st.columns(5)\n",
    "    kpi_card(c1, \"🚗\", \"Total Vehicles\", kpis[\"total\"], \"Last 5 min\", \"#3b82f6\")\n",
    "    kpi_card(c2, \"🚘\", \"Cars\", kpis[\"cars\"], color=\"#5fa8f5\")\n",
    "    kpi_card(c3, \"🚌\", \"Bus\", kpis[\"bus\"], color=\"#e67e22\")\n",
    "    kpi_card(c4, \"🚚\", \"Truck\", kpis[\"truck\"], color=\"#e74c3c\")\n",
    "    kpi_card(c5, \"🏍️\", \"Bike\", kpis[\"bikes\"], color=\"#f1c40f\")\n",
    "\n",
    "    st.write(\"\")\n",
    "    c6, c7, c8, c9 = st.columns(4)\n",
    "    kpi_card(c6, \"⚡\", \"Average Speed\", f'{kpis[\"avg_speed\"]} km/h', color=\"#2ecc71\")\n",
    "\n",
    "    density_color = DENSITY_COLORS[kpis[\"density\"]]\n",
    "    with c7:\n",
    "        st.markdown(f\"\"\"\n",
    "        <div class=\"kpi-card\">\n",
    "            <div class=\"kpi-icon\">🚦</div>\n",
    "            <div class=\"kpi-label\">Current Density</div>\n",
    "            <div class=\"status-pill\" style=\"background:{density_color}22; color:{density_color}; border:1px solid {density_color};\">\n",
    "                {kpis[\"density\"]}\n",
    "            </div>\n",
    "        </div>\n",
    "        \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    signal_color = {\"GREEN\": \"#2ecc71\", \"YELLOW\": \"#f1c40f\", \"RED\": \"#e74c3c\"}[kpis[\"signal\"]]\n",
    "    with c8:\n",
    "        st.markdown(f\"\"\"\n",
    "        <div class=\"kpi-card\">\n",
    "            <div class=\"kpi-icon\">🚥</div>\n",
    "            <div class=\"kpi-label\">Signal Status</div>\n",
    "            <div class=\"status-pill\" style=\"background:{signal_color}22; color:{signal_color}; border:1px solid {signal_color};\">\n",
    "                {kpis[\"signal\"]}\n",
    "            </div>\n",
    "        </div>\n",
    "        \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    emergency_text = \"ACTIVE 🚨\" if kpis[\"emergency\"] else \"NORMAL\"\n",
    "    emergency_color = \"#e74c3c\" if kpis[\"emergency\"] else \"#2ecc71\"\n",
    "    with c9:\n",
    "        st.markdown(f\"\"\"\n",
    "        <div class=\"kpi-card\">\n",
    "            <div class=\"kpi-icon\">🆘</div>\n",
    "            <div class=\"kpi-label\">Emergency Status</div>\n",
    "            <div class=\"status-pill\" style=\"background:{emergency_color}22; color:{emergency_color}; border:1px solid {emergency_color};\">\n",
    "                {emergency_text}\n",
    "            </div>\n",
    "        </div>\n",
    "        \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    st.write(\"\")\n",
    "    st.markdown('<div class=\"section-title\">Traffic Overview</div>', unsafe_allow_html=True)\n",
    "\n",
    "    col_a, col_b = st.columns([1, 1])\n",
    "    with col_a:\n",
    "        dist_df = generate_vehicle_distribution(kpis)\n",
    "        fig = px.pie(dist_df, names=\"Type\", values=\"Count\", hole=0.55,\n",
    "                     color=\"Type\", color_discrete_map=VEHICLE_COLORS,\n",
    "                     title=\"Vehicle Distribution\")\n",
    "        fig.update_traces(textinfo=\"percent+label\")\n",
    "        st.plotly_chart(style_fig(fig), use_container_width=True)\n",
    "\n",
    "    with col_b:\n",
    "        hourly_df = generate_hourly_traffic()\n",
    "        fig2 = px.area(hourly_df, x=\"Hour\", y=\"Vehicles\", title=\"Hourly Traffic Volume\")\n",
    "        fig2.update_traces(line_color=\"#3b82f6\", fillcolor=\"rgba(59,130,246,0.25)\")\n",
    "        st.plotly_chart(style_fig(fig2), use_container_width=True)\n",
    "\n",
    "    col_c, col_d = st.columns([1, 1])\n",
    "    with col_c:\n",
    "        density_df = generate_density_trend()\n",
    "        fig3 = px.line(density_df, x=\"Time\", y=\"VehicleCount\", title=\"Density Trend (last 2.5 hrs)\",\n",
    "                        markers=True)\n",
    "        fig3.update_traces(line_color=\"#e67e22\")\n",
    "        st.plotly_chart(style_fig(fig3), use_container_width=True)\n",
    "\n",
    "    with col_d:\n",
    "        lane_df = generate_lane_counts()\n",
    "        fig4 = px.bar(lane_df, x=\"Lane\", y=\"VehicleCount\", title=\"Lane-wise Vehicle Count\",\n",
    "                       color=\"VehicleCount\", color_continuous_scale=\"Blues\")\n",
    "        st.plotly_chart(style_fig(fig4), use_container_width=True)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PAGE: LIVE DETECTION\n",
    "# ============================================================\n",
    "elif page == \"🎥 Live Detection\":\n",
    "    st.markdown(\"# Live Detection Feed\")\n",
    "    st.caption(\"Simulated feed — connects to detector.py + tracker.py in the AI integration pass\")\n",
    "\n",
    "    col_video, col_info = st.columns([2, 1])\n",
    "\n",
    "    with col_video:\n",
    "        st.markdown('<div class=\"panel\">', unsafe_allow_html=True)\n",
    "        st.markdown(\"#### 📹 Camera Feed — Junction A\")\n",
    "        st.image(\n",
    "            \"https://placehold.co/960x540/0f1524/3b82f6?text=Live+Camera+Feed+%28Simulated%29\",\n",
    "            use_container_width=True,\n",
    "        )\n",
    "        b1, b2, b3 = st.columns(3)\n",
    "        b1.button(\"▶️ Start Feed\", use_container_width=True)\n",
    "        b2.button(\"⏸️ Pause\", use_container_width=True)\n",
    "        b3.button(\"⏹️ Stop\", use_container_width=True)\n",
    "        st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "    with col_info:\n",
    "        kpis = generate_kpis()\n",
    "        st.markdown('<div class=\"panel\">', unsafe_allow_html=True)\n",
    "        st.markdown(\"#### Frame Stats\")\n",
    "        st.metric(\"FPS\", f\"{random.randint(24, 30)}\")\n",
    "        st.metric(\"Vehicles in Frame\", kpis[\"total\"] % 40 + 5)\n",
    "        st.metric(\"Current Density\", kpis[\"density\"])\n",
    "        st.metric(\"Signal Timer\", f\"{random.randint(5, 60)}s\")\n",
    "        if kpis[\"emergency\"]:\n",
    "            st.error(\"🚨 Emergency Vehicle Detected — Lane 2\")\n",
    "        else:\n",
    "            st.success(\"✅ No Emergency Vehicles\")\n",
    "        st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "    st.write(\"\")\n",
    "    st.markdown('<div class=\"section-title\">Detected Objects (current frame)</div>', unsafe_allow_html=True)\n",
    "    obj_rows = []\n",
    "    for i in range(random.randint(6, 12)):\n",
    "        obj_rows.append({\n",
    "            \"Track ID\": random.randint(100, 999),\n",
    "            \"Type\": random.choice([\"Car\", \"Bike\", \"Bus\", \"Truck\", \"Person\"]),\n",
    "            \"Lane\": random.choice([1, 2, 3]),\n",
    "            \"Speed (km/h)\": round(random.uniform(10, 75), 1),\n",
    "            \"Confidence\": f\"{random.uniform(0.75, 0.98):.2f}\",\n",
    "        })\n",
    "    st.dataframe(pd.DataFrame(obj_rows), use_container_width=True, hide_index=True)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PAGE: ANALYTICS\n",
    "# ============================================================\n",
    "elif page == \"📈 Analytics\":\n",
    "    st.markdown(\"# Traffic Analytics\")\n",
    "    st.caption(\"Historical trends and breakdowns\")\n",
    "\n",
    "    kpis = generate_kpis()\n",
    "\n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        dist_df = generate_vehicle_distribution(kpis)\n",
    "        fig = px.bar(dist_df, x=\"Type\", y=\"Count\", color=\"Type\",\n",
    "                     color_discrete_map=VEHICLE_COLORS, title=\"Vehicle Type Distribution\")\n",
    "        st.plotly_chart(style_fig(fig), use_container_width=True)\n",
    "\n",
    "    with col2:\n",
    "        hourly_df = generate_hourly_traffic()\n",
    "        fig2 = px.line(hourly_df, x=\"Hour\", y=\"Vehicles\", title=\"Hourly Traffic Pattern\", markers=True)\n",
    "        fig2.update_traces(line_color=\"#3b82f6\")\n",
    "        peak_hour = hourly_df.loc[hourly_df[\"Vehicles\"].idxmax(), \"Hour\"]\n",
    "        st.plotly_chart(style_fig(fig2), use_container_width=True)\n",
    "        st.info(f\"📌 Peak Hour: **{peak_hour}**\")\n",
    "\n",
    "    col3, col4 = st.columns(2)\n",
    "    with col3:\n",
    "        density_df = generate_density_trend()\n",
    "        fig3 = px.bar(density_df, x=\"Time\", y=\"VehicleCount\", color=\"Density\",\n",
    "                       color_discrete_map=DENSITY_COLORS, title=\"Density Trend\")\n",
    "        st.plotly_chart(style_fig(fig3), use_container_width=True)\n",
    "\n",
    "    with col4:\n",
    "        speed_df = generate_speed_data()\n",
    "        fig4 = px.line(speed_df, x=\"Time\", y=\"AvgSpeed\", title=\"Average Speed Over Time\", markers=True)\n",
    "        fig4.add_hline(y=60, line_dash=\"dash\", line_color=\"#e74c3c\",\n",
    "                        annotation_text=\"Speed Limit (60 km/h)\")\n",
    "        fig4.update_traces(line_color=\"#2ecc71\")\n",
    "        st.plotly_chart(style_fig(fig4), use_container_width=True)\n",
    "\n",
    "    st.markdown('<div class=\"section-title\">Lane-wise Analysis & Heatmap</div>', unsafe_allow_html=True)\n",
    "    col5, col6 = st.columns(2)\n",
    "    with col5:\n",
    "        lane_df = generate_lane_counts()\n",
    "        fig5 = px.bar(lane_df, x=\"Lane\", y=\"VehicleCount\", color=\"Lane\", title=\"Lane-wise Count\")\n",
    "        st.plotly_chart(style_fig(fig5), use_container_width=True)\n",
    "\n",
    "    with col6:\n",
    "        heat_data = np.random.randint(5, 60, size=(7, 24))\n",
    "        days = [\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\"]\n",
    "        hours = [f\"{h}:00\" for h in range(24)]\n",
    "        fig6 = go.Figure(data=go.Heatmap(z=heat_data, x=hours, y=days, colorscale=\"Blues\"))\n",
    "        fig6.update_layout(title=\"Weekly Traffic Heatmap\")\n",
    "        st.plotly_chart(style_fig(fig6), use_container_width=True)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PAGE: REPORTS\n",
    "# ============================================================\n",
    "elif page == \"📄 Reports\":\n",
    "    st.markdown(\"# Reports & Violations\")\n",
    "    st.caption(\"Generate and export traffic reports\")\n",
    "\n",
    "    tab1, tab2 = st.tabs([\"📋 Violation Log\", \"📦 Export Reports\"])\n",
    "\n",
    "    with tab1:\n",
    "        viol_df = generate_violation_log()\n",
    "        f1, f2 = st.columns([1, 3])\n",
    "        with f1:\n",
    "            type_filter = st.selectbox(\"Filter by type\", [\"All\"] + list(viol_df[\"Type\"].unique()))\n",
    "        if type_filter != \"All\":\n",
    "            viol_df = viol_df[viol_df[\"Type\"] == type_filter]\n",
    "        st.dataframe(viol_df, use_container_width=True, hide_index=True)\n",
    "\n",
    "        c1, c2, c3 = st.columns(3)\n",
    "        c1.metric(\"Total Violations (24h)\", len(viol_df))\n",
    "        c2.metric(\"Most Common\", viol_df[\"Type\"].mode()[0] if not viol_df.empty else \"-\")\n",
    "        c3.metric(\"Locations Monitored\", viol_df[\"Location\"].nunique() if not viol_df.empty else 0)\n",
    "\n",
    "    with tab2:\n",
    "        st.markdown(\"#### Export current data\")\n",
    "        colf1, colf2, colf3 = st.columns(3)\n",
    "        with colf1:\n",
    "            st.markdown(\"**CSV Export**\")\n",
    "            csv_data = generate_violation_log().to_csv(index=False).encode(\"utf-8\")\n",
    "            st.download_button(\"⬇️ Download CSV\", csv_data, \"traffic_report.csv\", \"text/csv\",\n",
    "                                use_container_width=True)\n",
    "        with colf2:\n",
    "            st.markdown(\"**Excel Export**\")\n",
    "            st.button(\"⬇️ Download Excel\", use_container_width=True,\n",
    "                       help=\"Wired to analytics.py export function in the AI integration pass\")\n",
    "        with colf3:\n",
    "            st.markdown(\"**PDF Export**\")\n",
    "            st.button(\"⬇️ Download PDF\", use_container_width=True,\n",
    "                       help=\"Wired to analytics.py export function in the AI integration pass\")\n",
    "\n",
    "        st.markdown(\"---\")\n",
    "        st.markdown(\"#### Report Preview\")\n",
    "        summary_df = pd.DataFrame({\n",
    "            \"Metric\": [\"Total Vehicles\", \"Total Violations\", \"Average Speed\", \"Peak Hour\", \"Most Congested Lane\"],\n",
    "            \"Value\": [random.randint(1000, 3000), random.randint(20, 80),\n",
    "                      f\"{random.uniform(35, 55):.1f} km/h\", \"18:00\", \"Lane 2\"],\n",
    "        })\n",
    "        st.table(summary_df)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PAGE: PREDICTION\n",
    "# ============================================================\n",
    "elif page == \"🔮 Prediction\":\n",
    "    st.markdown(\"# Traffic Prediction\")\n",
    "    st.caption(\"ML-based short-term forecasting — will connect to prediction.py (Random Forest / XGBoost / Linear Regression)\")\n",
    "\n",
    "    col1, col2 = st.columns([2, 1])\n",
    "    with col1:\n",
    "        pred_df = generate_prediction_data()\n",
    "        fig = px.line(pred_df, x=\"Time\", y=\"PredictedVolume\", markers=True,\n",
    "                       title=\"Predicted Traffic Volume (Next 30 min)\")\n",
    "        fig.update_traces(line_color=\"#8b5cf6\")\n",
    "        st.plotly_chart(style_fig(fig), use_container_width=True)\n",
    "\n",
    "    with col2:\n",
    "        st.markdown('<div class=\"panel\">', unsafe_allow_html=True)\n",
    "        st.markdown(\"#### Model Info\")\n",
    "        model_choice = st.selectbox(\"Active Model\", [\"Random Forest\", \"XGBoost\", \"Linear Regression\"])\n",
    "        st.metric(\"Model Accuracy (R²)\", f\"{random.uniform(0.82, 0.95):.2f}\")\n",
    "        st.metric(\"Next 5 min\", f\"{random.randint(60, 200)} vehicles\")\n",
    "        st.metric(\"Next 10 min\", f\"{random.randint(60, 200)} vehicles\")\n",
    "        recommended = random.choice([\"20s\", \"40s\", \"60s\", \"90s\"])\n",
    "        st.metric(\"Recommended Signal Timing\", recommended)\n",
    "        st.markdown('</div>', unsafe_allow_html=True)\n",
    "\n",
    "    st.markdown('<div class=\"section-title\">Historical vs Predicted</div>', unsafe_allow_html=True)\n",
    "    hourly_df = generate_hourly_traffic()\n",
    "    hist_hours = hourly_df[\"Hour\"].tolist()[-6:]\n",
    "    hist_vals = hourly_df[\"Vehicles\"].tolist()[-6:]\n",
    "    combined = pd.DataFrame({\n",
    "        \"Time\": hist_hours + pred_df[\"Time\"].tolist(),\n",
    "        \"Vehicles\": hist_vals + pred_df[\"PredictedVolume\"].tolist(),\n",
    "        \"Type\": [\"Historical\"] * 6 + [\"Predicted\"] * len(pred_df),\n",
    "    })\n",
    "    fig2 = px.line(combined, x=\"Time\", y=\"Vehicles\", color=\"Type\", markers=True,\n",
    "                    color_discrete_map={\"Historical\": \"#3b82f6\", \"Predicted\": \"#8b5cf6\"})\n",
    "    st.plotly_chart(style_fig(fig2), use_container_width=True)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PAGE: SETTINGS\n",
    "# ============================================================\n",
    "elif page == \"⚙️ Settings\":\n",
    "    st.markdown(\"# Settings\")\n",
    "    st.caption(\"System configuration\")\n",
    "\n",
    "    tab1, tab2, tab3 = st.tabs([\"🎯 Detection\", \"🚦 Signal Timing\", \"🔔 Alerts\"])\n",
    "\n",
    "    with tab1:\n",
    "        st.markdown(\"#### Detection Parameters\")\n",
    "        st.slider(\"Confidence Threshold\", 0.0, 1.0, 0.35, 0.05)\n",
    "        st.slider(\"IOU Threshold\", 0.0, 1.0, 0.45, 0.05)\n",
    "        st.selectbox(\"YOLO Model\", [\"yolov8n.pt\", \"yolov8s.pt\", \"yolov8m.pt\", \"yolov8l.pt\"])\n",
    "        st.multiselect(\"Classes to Detect\",\n",
    "                        [\"Car\", \"Truck\", \"Bus\", \"Motorcycle\", \"Bicycle\", \"Person\", \"Traffic Light\", \"Stop Sign\"],\n",
    "                        default=[\"Car\", \"Truck\", \"Bus\", \"Motorcycle\", \"Bicycle\"])\n",
    "\n",
    "    with tab2:\n",
    "        st.markdown(\"#### Signal Timing Rules (seconds)\")\n",
    "        c1, c2, c3, c4 = st.columns(4)\n",
    "        c1.number_input(\"Low density\", value=20)\n",
    "        c2.number_input(\"Medium density\", value=40)\n",
    "        c3.number_input(\"High density\", value=60)\n",
    "        c4.number_input(\"Very High density\", value=90)\n",
    "        st.number_input(\"Speed Limit (km/h)\", value=60)\n",
    "        st.number_input(\"Pixels per Meter (calibration)\", value=8.0)\n",
    "\n",
    "    with tab3:\n",
    "        st.markdown(\"#### Alert Preferences\")\n",
    "        st.checkbox(\"Emergency vehicle sound alert\", value=True)\n",
    "        st.checkbox(\"Red light violation alerts\", value=True)\n",
    "        st.checkbox(\"Overspeed alerts\", value=True)\n",
    "        st.checkbox(\"Illegal parking alerts\", value=False)\n",
    "        st.text_input(\"Alert notification email\")\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    st.button(\"💾 Save Settings\", type=\"primary\")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PAGE: ABOUT\n",
    "# ============================================================\n",
    "elif page == \"ℹ️ About\":\n",
    "    st.markdown(\"# About This System\")\n",
    "    st.markdown(\"\"\"\n",
    "    <div class=\"panel\">\n",
    "    <h4>AI-Based Intelligent Traffic Monitoring and Smart Traffic Signal Management System</h4>\n",
    "    <p>A final-year Smart City project combining computer vision, machine learning, and\n",
    "    real-time analytics to monitor traffic, manage adaptive signal timing, and detect\n",
    "    violations automatically.</p>\n",
    "    <p><b>Core Modules:</b> YOLOv8 Detection • ByteTrack Multi-Object Tracking • Density Classification\n",
    "    • Adaptive Signal Control • Speed Estimation • Emergency Vehicle Priority • Violation Detection\n",
    "    • ML-based Traffic Prediction</p>\n",
    "    <p><b>Tech Stack:</b> Python, YOLOv8, OpenCV, Streamlit, SQLite, Plotly, Scikit-Learn</p>\n",
    "    </div>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    st.markdown(\"#### System Architecture\")\n",
    "    st.graphviz_chart(\"\"\"\n",
    "    digraph {\n",
    "        rankdir=LR;\n",
    "        bgcolor=\"transparent\";\n",
    "        node [shape=box, style=\"rounded,filled\", fillcolor=\"#131a2b\", fontcolor=\"#e6e9f0\", color=\"#3b82f6\"];\n",
    "        edge [color=\"#8b94ab\"];\n",
    "        Camera -> Detector [label=\"frames\"];\n",
    "        Detector -> Tracker;\n",
    "        Tracker -> Density;\n",
    "        Density -> SignalController;\n",
    "        Tracker -> SpeedEstimator;\n",
    "        Tracker -> ViolationModules;\n",
    "        SignalController -> Dashboard;\n",
    "        SpeedEstimator -> Dashboard;\n",
    "        ViolationModules -> Dashboard;\n",
    "        Density -> Dashboard;\n",
    "        Dashboard -> Database;\n",
    "        Database -> Prediction;\n",
    "        Prediction -> Dashboard;\n",
    "    }\n",
    "    \"\"\")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# FOOTER\n",
    "# ============================================================\n",
    "st.markdown('<div class=\"footer-tag\">Smart Traffic Control System • Running on simulated data • v0.1</div>',\n",
    "            unsafe_allow_html=True)\n",
    "\n",
    "if auto_refresh:\n",
    "    time.sleep(5)\n",
    "    st.rerun()"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
