{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d206f68",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "%%writefile database.py\n",
    "\"\"\"\n",
    "SQLite persistence layer for the Traffic Monitoring System.\n",
    "\"\"\"\n",
    "\n",
    "import sqlite3\n",
    "from datetime import datetime\n",
    "from contextlib import contextmanager\n",
    "from config import DB_PATH\n",
    "\n",
    "\n",
    "class Database:\n",
    "    def __init__(self, db_path: str = DB_PATH):\n",
    "        self.db_path = db_path\n",
    "        self._init_tables()\n",
    "\n",
    "    @contextmanager\n",
    "    def _connect(self):\n",
    "        conn = sqlite3.connect(self.db_path)\n",
    "        try:\n",
    "            yield conn\n",
    "            conn.commit()\n",
    "        finally:\n",
    "            conn.close()\n",
    "\n",
    "    def _init_tables(self):\n",
    "        schema = \"\"\"\n",
    "        CREATE TABLE IF NOT EXISTS vehicle_events (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            track_id INTEGER,\n",
    "            vehicle_type TEXT,\n",
    "            lane INTEGER,\n",
    "            timestamp TEXT\n",
    "        );\n",
    "\n",
    "        CREATE TABLE IF NOT EXISTS density_log (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            vehicle_count INTEGER,\n",
    "            density_level TEXT,\n",
    "            timestamp TEXT\n",
    "        );\n",
    "\n",
    "        CREATE TABLE IF NOT EXISTS speed_log (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            track_id INTEGER,\n",
    "            vehicle_type TEXT,\n",
    "            speed_kmph REAL,\n",
    "            overspeed INTEGER,\n",
    "            timestamp TEXT\n",
    "        );\n",
    "\n",
    "        CREATE TABLE IF NOT EXISTS violations (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            violation_type TEXT,\n",
    "            track_id INTEGER,\n",
    "            screenshot_path TEXT,\n",
    "            timestamp TEXT\n",
    "        );\n",
    "\n",
    "        CREATE TABLE IF NOT EXISTS signal_log (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            density_level TEXT,\n",
    "            signal_duration INTEGER,\n",
    "            timestamp TEXT\n",
    "        );\n",
    "\n",
    "        CREATE TABLE IF NOT EXISTS prediction_log (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            horizon_minutes INTEGER,\n",
    "            predicted_volume REAL,\n",
    "            timestamp TEXT\n",
    "        );\n",
    "\n",
    "        CREATE TABLE IF NOT EXISTS emergency_log (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            vehicle_type TEXT,\n",
    "            lane INTEGER,\n",
    "            timestamp TEXT\n",
    "        );\n",
    "        \"\"\"\n",
    "        with self._connect() as conn:\n",
    "            conn.executescript(schema)\n",
    "\n",
    "    def log_vehicle_event(self, track_id, vehicle_type, lane):\n",
    "        with self._connect() as conn:\n",
    "            conn.execute(\n",
    "                \"INSERT INTO vehicle_events (track_id, vehicle_type, lane, timestamp) VALUES (?,?,?,?)\",\n",
    "                (track_id, vehicle_type, lane, datetime.now().isoformat()),\n",
    "            )\n",
    "\n",
    "    def log_density(self, vehicle_count, density_level):\n",
    "        with self._connect() as conn:\n",
    "            conn.execute(\n",
    "                \"INSERT INTO density_log (vehicle_count, density_level, timestamp) VALUES (?,?,?)\",\n",
    "                (vehicle_count, density_level, datetime.now().isoformat()),\n",
    "            )\n",
    "\n",
    "    def log_speed(self, track_id, vehicle_type, speed_kmph, overspeed):\n",
    "        with self._connect() as conn:\n",
    "            conn.execute(\n",
    "                \"INSERT INTO speed_log (track_id, vehicle_type, speed_kmph, overspeed, timestamp) VALUES (?,?,?,?,?)\",\n",
    "                (track_id, vehicle_type, speed_kmph, int(overspeed), datetime.now().isoformat()),\n",
    "            )\n",
    "\n",
    "    def log_violation(self, violation_type, track_id, screenshot_path):\n",
    "        with self._connect() as conn:\n",
    "            conn.execute(\n",
    "                \"INSERT INTO violations (violation_type, track_id, screenshot_path, timestamp) VALUES (?,?,?,?)\",\n",
    "                (violation_type, track_id, screenshot_path, datetime.now().isoformat()),\n",
    "            )\n",
    "\n",
    "    def log_signal(self, density_level, signal_duration):\n",
    "        with self._connect() as conn:\n",
    "            conn.execute(\n",
    "                \"INSERT INTO signal_log (density_level, signal_duration, timestamp) VALUES (?,?,?)\",\n",
    "                (density_level, signal_duration, datetime.now().isoformat()),\n",
    "            )\n",
    "\n",
    "    def log_emergency(self, vehicle_type, lane):\n",
    "        with self._connect() as conn:\n",
    "            conn.execute(\n",
    "                \"INSERT INTO emergency_log (vehicle_type, lane, timestamp) VALUES (?,?,?)\",\n",
    "                (vehicle_type, lane, datetime.now().isoformat()),\n",
    "            )\n",
    "\n",
    "    def fetch_all(self, table: str, limit: int = 500):\n",
    "        with self._connect() as conn:\n",
    "            cur = conn.execute(f\"SELECT * FROM {table} ORDER BY id DESC LIMIT ?\", (limit,))\n",
    "            cols = [d[0] for d in cur.description]\n",
    "            rows = cur.fetchall()\n",
    "        return cols, rows"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
